### ISSUE TITLE
You forgot to remove a comment from your code. Come see me at the office tomorrow morning when you arrive!

### ISSUE THREAD

**Issue by parphane** [FraPar/P10_API#1]
https://github.com/FraPar/P10_API/blob/584751fbc452d29872170e7999393c97794c8f8e/api_project/api/views.py#L136

**Comment by parphane** [comment]
You better bring cookies and coffee to make up for it!

**Comment by FraPar** [comment]
Qu'est ce que tu branles sur mon projet? 🤣

Le sam. 13 nov. 2021 à 03:12, Stéphane PARENTI ***@***.***> a
écrit :

**Comment by parphane** [comment]
Cookies and coffee delivered. Closing the issue. :)
